In [60]:
import os
print(os.listdir("/content"))

['.config', 'adult.data', 'sample_data']

In [61]:
import pandas as pd

file_path = "/content/adult.data"

df = pd.read_csv(file_path, header=None, skipinitialspace=True)

print("Dataset loaded successfully!")
print("First 5 rows:")
display(df.head())

Dataset loaded successfully!
First 5 rows:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [62]:
column_names = [
    "age", "workclass", "fnlwgt", "education",
    "education_num", "marital_status", "occupation",
    "relationship", "race", "sex", "capital_gain",
    "capital_loss", "hours_per_week", "native_country",
    "income"
]

df.columns = column_names

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset shape: (32561, 15)

Column names:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income']

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [63]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:")
print(df.isnull().sum().sum())

Missing values in each column:
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

Total missing values:
0

In [64]:
# Count question marks in each column
missing_counts = (df == "?").sum()

print("Missing entries marked with '?':")
print(missing_counts[missing_counts > 0])

print("\nTotal missing entries:", missing_counts.sum())

Missing entries marked with '?':
workclass         1836
occupation        1843
native_country     583
dtype: int64

Total missing entries: 4262

In [65]:
# Replace '?' with proper missing values
df.replace("?", pd.NA, inplace=True)

# Count missing values after replacement
print("Missing values after replacement:")
print(df.isnull().sum())

# Remove rows containing missing values
df_cleaned = df.dropna().copy()

print("\nOriginal dataset shape:", df.shape)
print("Cleaned dataset shape:", df_cleaned.shape)
print("Rows removed:", len(df) - len(df_cleaned))

Missing values after replacement:
age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

Original dataset shape: (32561, 15)
Cleaned dataset shape: (30162, 15)
Rows removed: 2399

In [66]:
# Count duplicate rows
duplicate_count = df_cleaned.duplicated().sum()

print("Duplicate rows found:", duplicate_count)

# Remove duplicate rows
df_cleaned = df_cleaned.drop_duplicates().copy()

print("Shape after removing duplicates:", df_cleaned.shape)
print("Remaining duplicate rows:", df_cleaned.duplicated().sum())

Duplicate rows found: 23
Shape after removing duplicates: (30139, 15)
Remaining duplicate rows: 0

In [67]:
print("Data types before correction:")
print(df_cleaned.dtypes)

# Convert numerical columns to numeric types
numeric_columns = [
    "age", "fnlwgt", "education_num",
    "capital_gain", "capital_loss", "hours_per_week"
]

for column in numeric_columns:
    df_cleaned[column] = pd.to_numeric(
        df_cleaned[column], errors="coerce"
    )

print("\nData types after correction:")
print(df_cleaned.dtypes)

Data types before correction:
age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

Data types after correction:
age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [68]:
# Remove unnecessary spaces from text columns
text_columns = df_cleaned.select_dtypes(
    include="object"
).columns

for column in text_columns:
    df_cleaned[column] = df_cleaned[column].str.strip()

# Inspect unique values in important columns
print("Workclass categories:")
print(df_cleaned["workclass"].unique())

print("\nOccupation categories:")
print(df_cleaned["occupation"].unique())

print("\nIncome categories:")
print(df_cleaned["income"].unique())

Workclass categories:
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov'
 'Self-emp-inc' 'Without-pay']

Occupation categories:
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Transport-moving' 'Farming-fishing'
 'Machine-op-inspct' 'Tech-support' 'Craft-repair' 'Protective-serv'
 'Armed-Forces' 'Priv-house-serv']

Income categories:
['<=50K' '>50K']

In [69]:
print("Final dataset shape:", df_cleaned.shape)

print("\nMissing values remaining:")
print(df_cleaned.isnull().sum().sum())

print("\nDuplicate rows remaining:")
print(df_cleaned.duplicated().sum())

print("\nData types:")
print(df_cleaned.dtypes)

Final dataset shape: (30139, 15)

Missing values remaining:
0

Duplicate rows remaining:
0

Data types:
age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [70]:
# Save the cleaned dataset as a CSV file
output_file = "/content/cleaned_adult_data.csv"

df_cleaned.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File location:", output_file)

Cleaned dataset saved successfully!
File location: /content/cleaned_adult_data.csv